name: Compile main.typ
on: push
jobs:
  render-paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
        with:
          cache-dependency-path: requirements.typ
      # Now Typst is installed and packages will be cached!
      - run: typst compile main.typ example.pdf
      #- uses: actions/upload-artifact@v4
      #  with:
      #    name: paper
      #    path: paper.pdf
          
